project:
  type: website
  output-dir: docs

website:
  title: "Audrey Longan's e-Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: about.qmd
        text: "About Me"
      - href: Final_Stat210_Project/Final_Project.qmd
        text: "Project: STAT 210 Class Example"
        

format:
  html:
    theme:
      - yeti
      - brand
    css: styles.css
    toc: true

editor: source

