---
title: "About"
---

Growing up in California's San Joaquin Valley, surrounded by agriculture and mountainous landscapes, I decided to pursue a career as an environmental scientist and ecologist. I'm extremely passionate about environmental protection and I love being in nature, studying different aspects that make various natural environments so unique. I am also an artist, using my skills to draw different plants, insects, and natural landscapes that I have seen and studied. As a researcher, I am fascinated by plants and insects. I have applied for PhD programs after my graduation, focused on conservation ecology. 

## Education

California State University, Monterey Bay \| Seaside, CA

B.S. in Environmental Science, Technology, and Policy \| Minors in Statistics and Biology \| Applied Ecology Concentration \| Expected May 2026

## Experience

Undergraduate Research Assistant \| Watershed, Environments, and Ecology Lab \| Aug 2023 - Present

Restoration and Education Assistant \| Habitat Stewardship Project Monterey Bay \| Aug 2022 - Present

Undergraduate Research Assistant \| Fundación para la Conservación de los Andes Tropicales (FCAT) \| Jan 2026

Undergraduate REU Researcher \| Environmental Endocrinology Lab \| Northern Arizona University \| May 2025 - Aug 2025

Service Learner \| Big Sur Land Trust \| Sep 2024 - Nov 2024
