---
title: "Final Project: Part 1"
author: "Audrey Longan"
date: 3-17-26
---

# Data Description

1.  Identify your data source.

> My honors capstone data will be used for this project, that I have collected from the spring of 2025 until the end of fall 2025.

2.  Describe your data, including variables and data types.

> -   The dataset has 279 rows and 28 variables, 11 character variables, 15 double variables, and 2 time variables.
>
> -   Methods for Data Collection and variables collected:
>
>     -   Do a 50 m transect on both sides of the river, 1 meter out from shore, recorded plants every time seen, within 1 meters of each side of the tape (overall 4 meters recorded)
>
>     -   When a stream is less than or equal to 2 meters wide, I only surveyed one transect in the middle of the river, to cover the full two meters.
>
>         -   Every time plant is found measure:
>
>             -   Depth (m)
>
>             -   Velocity (m/s)
>
>             -   Substrate size (mm)
>
>             -   Plant name and number of individuals or range/cover area on the transect
>
>         -   Measure at each transect overall:
>
>             -   canopy cover facing north, south, east, and west, and averaged over all 4, then multiplied by 4 and divided by product of 17\*4 (freshwater ecology standard)
>
>             -   the percentage of the 50-meter transects that are riffle, pool, run, or glide.
>
>             -   water temperature (°C)
>
>             -   pH
>
>             -   conductivity(ms/cm)
>
>             -   TDS (g/L)
>
>             -   Dissolved oxygen (mg/L) and Dissolved oxygen (%)
>
>             -   salinity

3.  Identify the research questions you want to answer.

> (1) How does abundance and diversity differ between site and transect? (2) Are there different environmental conditions that support specific species? (3) Which environmental factors lead to higher diversity? (4) Where do taxa tend to occur when they are not ubiquitous or rare?

# Data Visualization

1.  What do you want your final visualizations to look like?

> -   Violin plots with jittered points for abundance and diversity between locations and transects
>
> -   dodged barchart showing average values of environmental variables with a fill of presence absence for important species to compare
>
> -   scatterplots with model regression lines for showing relationships between environmental factors and abundance as well as presence absence
>
> -   additional scatterplots showing regression lines for relationships of abundance of a specific species against important environmental factors
>
> -   possibly a table of values from eventual linear model output and random forest modelling output

2.  What do you want to highlight on your final visualizations in order to answer your research questions? How do you plan to do that?

> -   Highlights:
>
>     -   highlight the species with the most abundance and the species with the lowest abundance
>
>     -   highlight the highest abundances between sites
>
>     -   highlight any close relationships between environmental factors and abundance or presence absence
>
> -   My Plan:
>
>     -   ordering bars, violin plots, etc. from smallest to biggest (using the mean to do this task with violin plots)
>
>     -   use annotations or bright colors to highlight important notes

3.  What is missing from your data or would need to change in your data to create these visualizations?

> -   Create a total abundance variable by combining the cover area and number of individuals variable
>
>     -   an estimate of abundance would be 30 cm in width for each individual, so each individual was about 900 cm\^2, so add this to the area counts
>
> -   Create a presence/absence column for every species at every site
>
> -   Join environmental variable columns to create separate datasets for presence/absence and abundance
>
> -   For substrate sizes: change \<2s to 1 (standard to use half of our limit number) and for numbers with a greater than symbol, use the lowest number, e.g.: change \>300, to 300
>
> -   For the velocity variable: change \<0.1 to 0.05; drop nas
>
> -   Treat NA depth as 0 depth
>
> -   Add a new column of rooted and floating by combining the values of emergent and submergent into one value of rooted! 
>
> -   Join additional environmental data taken from the online EPA StreamCat Database:
>
>     NHDPlus California Data Vector Processing, Unit 18. (2024) \[downloaded file\]. United States Environmental Protection Agency. Available by: <https://www.epa.gov/waterdata/nhdplus-california-data-vector-processing-unit-18> 
>
>     -   I will be reducing this data set to closely follow the Carmel River Watershed region, I am researching, in ArcGIS.

# Data Cleaning

1.  Do you need to reformat any variables into different types (e.g. factors, time, dates, strings)? Or remove information from variable values?

> Yes, I changed the substrate and velocity variables to remove "\>" or "\<" symbols so that they can be numeric variables. I did this with mutate().

2.  Do you need to deal with any missing data, especially missing data coded other than NA?

> Yes, I removed NA data from the velocity variable and change NA values in the depth variable to zero. There is not any missing data that is not coded as NA. I did this with mutate().

3.  Do you need to filter your data? How?

> No, I don't need to do any filtering.

4.  Do you need to create any new variables? What variables? How?

> -   using mutate()
>
> -   a stem count variable called calc_stem_abundance_m2 by multiplying number of individuals by 0.09 (accounting for each individual as 900 cm\^2 on average for an estimate)
>
> -   a final_abundance variable by using cover area when the value for number_individuals is NA or individuals are greater than or equal to 150 (this may be a less accurate estimate of individuals so using cover area is a better estimate in this case). I also added a clause for using the cover area variable instead of individuals for annual grass if individuals are greater than 5 (as it is difficult to count individual blades of grass)
>
> -   Add a new variable of rooted_v_floating by combining the values of emergent and submergent into one value of "rooted"
>
> -   creating a presence/absence column for each species at each site with 1 indicating presence

5.  Do you need to add new data (join) to your data? What data? How?

> Yes, I need to join additional environmental variables from the StreamCat dataset to my new abundance and presence/absence datasets. I will most likely use a left_join as I want to keep everything in the abundance and presence/absence datasets and only keep the data that matches from the StreamCat dataset. Greater understanding of how this will be accomplished will be known once I explore the StreamCat dataset further and determine exactly what needs to be done to join the datasets.

6.  Do you need pivot your data in any way? Why? How?

> Yes, I needed to pivot_wider to create the initial presence/absence matrix and then pivot_longer to add the environmental variables to the new presence/absence dataset.

7.  Do you need to summarize any of the variables? Which ones? How?

> Yes. I will be grouping my data by species, transect location and site. Then, I need to take the sum of the final_abundance, and calculate the mean for all my environmental variables, for each of the groupings.

8.  What other aspects of your data need to be “fixed” in order to make your data visualizations?

> I also used the janitor package to clean my variable names and make it easier to fully clean my data.

9.  Are there any variables you can exclude from your data?

> Yes, I excluded the variables: location_coordinates, date, observers, start_time, end_time, as they weren't important for my analysis.
